title: walkah
slogan: striving towards mediocrity
author: James Walker
url: http://walkah.net

auto: false
pygments: true
lsi: false
markdown: rdiscount
permalink: blog/:title
exclude: Gemfile, Gemfile.lock, Rakefile
